// Code generated by scripts/generate_endpoints.py; DO NOT EDIT.

package mlbapi

import "context"

var endpointNames = []string{
	"attendance",
	"awards",
	"conferences",
	"divisions",
	"draft",
	"game",
	"gamePace",
	"game_boxscore",
	"game_changes",
	"game_color",
	"game_color_diff",
	"game_color_timestamps",
	"game_content",
	"game_contextMetrics",
	"game_diff",
	"game_linescore",
	"game_playByPlay",
	"game_timestamps",
	"game_uniforms",
	"game_winProbability",
	"highLow",
	"homeRunDerby",
	"jobs",
	"jobs_datacasters",
	"jobs_officialScorers",
	"jobs_umpire_games",
	"jobs_umpires",
	"league",
	"league_allStarBallot",
	"league_allStarFinalVote",
	"league_allStarWriteIns",
	"meta",
	"people",
	"people_changes",
	"people_freeAgents",
	"person",
	"person_stats",
	"schedule",
	"schedule_postseason",
	"schedule_postseason_series",
	"schedule_postseason_tuneIn",
	"schedule_tied",
	"season",
	"seasons",
	"sports",
	"sports_players",
	"standings",
	"stats",
	"stats_leaders",
	"stats_streaks",
	"team",
	"team_alumni",
	"team_coaches",
	"team_leaders",
	"team_personnel",
	"team_roster",
	"team_stats",
	"team_uniforms",
	"teams",
	"teams_affiliates",
	"teams_history",
	"teams_stats",
	"transactions",
	"venue",
}

var defaultEndpoints = map[string]EndpointDefinition{
	"attendance": {
		Name:           "attendance",
		PathTemplate:   "{ver}/attendance",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"teamId", "leagueId", "season", "date", "leagueListId", "gameType", "fields"},
		RequiredParams: [][]string{{"teamId"}, {"leagueId"}, {"leagueListid"}},
		Note:           "",
	},
	"awards": {
		Name:           "awards",
		PathTemplate:   "{ver}/awards{awardId}{recipients}",
		PathParamOrder: []string{"ver", "awardId", "recipients"},
		PathParams: map[string]PathParamDefinition{
			"ver":        {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"awardId":    {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: true, TrailingSlash: false, Required: false},
			"recipients": {Type: "bool", Default: "/recipients", HasDefault: true, TrueValue: "/recipients", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: false},
		},
		QueryParams:    []string{"sportId", "leagueId", "season", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "Call awards endpoint with no parameters to return a list of awardIds.",
	},
	"conferences": {
		Name:           "conferences",
		PathTemplate:   "{ver}/conferences",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"conferenceId", "season", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"divisions": {
		Name:           "divisions",
		PathTemplate:   "{ver}/divisions",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"divisionId", "leagueId", "sportId", "season"},
		RequiredParams: [][]string{{}},
		Note:           "Call divisions endpoint with no parameters to return a list of divisions.",
	},
	"draft": {
		Name:           "draft",
		PathTemplate:   "{ver}/draft{prospects}{year}{latest}",
		PathParamOrder: []string{"ver", "prospects", "year", "latest"},
		PathParams: map[string]PathParamDefinition{
			"ver":       {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"prospects": {Type: "bool", Default: "", HasDefault: true, TrueValue: "/prospects", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: false},
			"year":      {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: true, TrailingSlash: false, Required: false},
			"latest":    {Type: "bool", Default: "", HasDefault: true, TrueValue: "/latest", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: false},
		},
		QueryParams:    []string{"limit", "fields", "round", "name", "school", "state", "country", "position", "teamId", "playerId", "bisPlayerId"},
		RequiredParams: [][]string{{}},
		Note:           "No query parameters are honored when \"latest\" endpoint is queried (year is still required). Prospects and Latest cannot be used together.",
	},
	"game": {
		Name:           "game",
		PathTemplate:   "{ver}/game/{gamePk}/feed/live",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1.1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"gamePace": {
		Name:           "gamePace",
		PathTemplate:   "{ver}/gamePace",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "teamIds", "leagueIds", "leagueListId", "sportId", "gameType", "startDate", "endDate", "venueIds", "orgType", "includeChildren", "fields"},
		RequiredParams: [][]string{{"season"}},
		Note:           "",
	},
	"game_boxscore": {
		Name:           "game_boxscore",
		PathTemplate:   "{ver}/game/{gamePk}/boxscore",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_changes": {
		Name:           "game_changes",
		PathTemplate:   "{ver}/game/changes",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"updatedSince", "sportId", "gameType", "season", "fields"},
		RequiredParams: [][]string{{"updatedSince"}},
		Note:           "",
	},
	"game_color": {
		Name:           "game_color",
		PathTemplate:   "{ver}/game/{gamePk}/feed/color",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_color_diff": {
		Name:           "game_color_diff",
		PathTemplate:   "{ver}/game/{gamePk}/feed/color/diffPatch",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"startTimecode", "endTimecode"},
		RequiredParams: [][]string{{"startTimeCode", "endTimeCode"}},
		Note:           "",
	},
	"game_color_timestamps": {
		Name:           "game_color_timestamps",
		PathTemplate:   "{ver}/game/{gamePk}/feed/color/timestamps",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_content": {
		Name:           "game_content",
		PathTemplate:   "{ver}/game/{gamePk}/content",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"highlightLimit"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_contextMetrics": {
		Name:           "game_contextMetrics",
		PathTemplate:   "{ver}/game/{gamePk}/contextMetrics",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_diff": {
		Name:           "game_diff",
		PathTemplate:   "{ver}/game/{gamePk}/feed/live/diffPatch",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1.1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"startTimecode", "endTimecode"},
		RequiredParams: [][]string{{"startTimecode", "endTimecode"}},
		Note:           "",
	},
	"game_linescore": {
		Name:           "game_linescore",
		PathTemplate:   "{ver}/game/{gamePk}/linescore",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_playByPlay": {
		Name:           "game_playByPlay",
		PathTemplate:   "{ver}/game/{gamePk}/playByPlay",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_timestamps": {
		Name:           "game_timestamps",
		PathTemplate:   "{ver}/game/{gamePk}/feed/live/timestamps",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1.1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"game_uniforms": {
		Name:           "game_uniforms",
		PathTemplate:   "{ver}/uniforms/game",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"gamePks", "fields"},
		RequiredParams: [][]string{{"gamePks"}},
		Note:           "",
	},
	"game_winProbability": {
		Name:           "game_winProbability",
		PathTemplate:   "{ver}/game/{gamePk}/winProbability",
		PathParamOrder: []string{"ver", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "If you only want the current win probability for each team, try the game_contextMetrics endpoint instad.",
	},
	"highLow": {
		Name:           "highLow",
		PathTemplate:   "{ver}/highLow/{orgType}",
		PathParamOrder: []string{"ver", "orgType"},
		PathParams: map[string]PathParamDefinition{
			"ver":     {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"orgType": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"statGroup", "sortStat", "season", "gameType", "teamId", "leagueId", "sportIds", "limit", "fields"},
		RequiredParams: [][]string{{"sortStat", "season"}},
		Note:           "Valid values for orgType parameter: player, team, division, league, sport, types.",
	},
	"homeRunDerby": {
		Name:           "homeRunDerby",
		PathTemplate:   "{ver}/homeRunDerby/{gamePk}{bracket}{pool}",
		PathParamOrder: []string{"ver", "gamePk", "bracket", "pool"},
		PathParams: map[string]PathParamDefinition{
			"ver":     {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk":  {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"bracket": {Type: "bool", Default: "", HasDefault: true, TrueValue: "/bracket", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: false},
			"pool":    {Type: "bool", Default: "", HasDefault: true, TrueValue: "/pool", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: false},
		},
		QueryParams:    []string{"fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"jobs": {
		Name:           "jobs",
		PathTemplate:   "{ver}/jobs",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"jobType", "sportId", "date", "fields"},
		RequiredParams: [][]string{{"jobType"}},
		Note:           "",
	},
	"jobs_datacasters": {
		Name:           "jobs_datacasters",
		PathTemplate:   "{ver}/jobs/datacasters",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"sportId", "date", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"jobs_officialScorers": {
		Name:           "jobs_officialScorers",
		PathTemplate:   "{ver}/jobs/officialScorers",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"timecode", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"jobs_umpire_games": {
		Name:           "jobs_umpire_games",
		PathTemplate:   "{ver}/jobs/umpires/games/{umpireId}",
		PathParamOrder: []string{"ver", "umpireId"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"umpireId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "fields"},
		RequiredParams: [][]string{{"season"}},
		Note:           "",
	},
	"jobs_umpires": {
		Name:           "jobs_umpires",
		PathTemplate:   "{ver}/jobs/umpires",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"sportId", "date", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"league": {
		Name:           "league",
		PathTemplate:   "{ver}/league",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"sportId", "leagueIds", "seasons", "fields"},
		RequiredParams: [][]string{{"sportId"}, {"leagueIds"}},
		Note:           "",
	},
	"league_allStarBallot": {
		Name:           "league_allStarBallot",
		PathTemplate:   "{ver}/league/{leagueId}/allStarBallot",
		PathParamOrder: []string{"ver", "leagueId"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"leagueId": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "fields"},
		RequiredParams: [][]string{{"season"}},
		Note:           "",
	},
	"league_allStarFinalVote": {
		Name:           "league_allStarFinalVote",
		PathTemplate:   "{ver}/league/{leagueId}/allStarFinalVote",
		PathParamOrder: []string{"ver", "leagueId"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"leagueId": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "fields"},
		RequiredParams: [][]string{{"season"}},
		Note:           "",
	},
	"league_allStarWriteIns": {
		Name:           "league_allStarWriteIns",
		PathTemplate:   "{ver}/league/{leagueId}/allStarWriteIns",
		PathParamOrder: []string{"ver", "leagueId"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"leagueId": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "fields"},
		RequiredParams: [][]string{{"season"}},
		Note:           "",
	},
	"meta": {
		Name:           "meta",
		PathTemplate:   "{ver}/{type}",
		PathParamOrder: []string{"ver", "type"},
		PathParams: map[string]PathParamDefinition{
			"ver":  {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"type": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"[]"},
		RequiredParams: [][]string{{}},
		Note:           "The meta endpoint is used to retrieve values to be used within other API calls. Available types: awards, baseballStats, eventTypes, gameStatus, gameTypes, hitTrajectories, jobTypes, languages, leagueLeaderTypes, logicalEvents, metrics, pitchCodes, pitchTypes, platforms, positions, reviewReasons, rosterTypes, scheduleEventTypes, situationCodes, sky, standingsTypes, statGroups, statTypes, windDirection.",
	},
	"people": {
		Name:           "people",
		PathTemplate:   "{ver}/people",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"personIds", "hydrate", "fields"},
		RequiredParams: [][]string{{"personIds"}},
		Note:           "",
	},
	"people_changes": {
		Name:           "people_changes",
		PathTemplate:   "{ver}/people/changes",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"updatedSince", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"people_freeAgents": {
		Name:           "people_freeAgents",
		PathTemplate:   "{ver}/people/freeAgents",
		PathParamOrder: []string{"ver", "leagueId"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"leagueId": {Type: "str", Default: "", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"order", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"person": {
		Name:           "person",
		PathTemplate:   "{ver}/people/{personId}",
		PathParamOrder: []string{"ver", "personId"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"personId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"person_stats": {
		Name:           "person_stats",
		PathTemplate:   "{ver}/people/{personId}/stats/game/{gamePk}",
		PathParamOrder: []string{"ver", "personId", "gamePk"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"personId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"gamePk":   {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"fields"},
		RequiredParams: [][]string{{}},
		Note:           "Specify \"current\" instead of a gamePk for a player's current game stats.",
	},
	"schedule": {
		Name:           "schedule",
		PathTemplate:   "{ver}/schedule",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"scheduleType", "eventTypes", "hydrate", "teamId", "leagueId", "sportId", "gamePk", "gamePks", "venueIds", "gameTypes", "date", "startDate", "endDate", "opponentId", "fields", "season"},
		RequiredParams: [][]string{{"sportId"}, {"gamePk"}, {"gamePks"}},
		Note:           "",
	},
	"schedule_postseason": {
		Name:           "schedule_postseason",
		PathTemplate:   "{ver}/schedule/postseason",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"gameTypes", "seriesNumber", "teamId", "sportId", "season", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"schedule_postseason_series": {
		Name:           "schedule_postseason_series",
		PathTemplate:   "{ver}/schedule/postseason/series",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"gameTypes", "seriesNumber", "teamId", "sportId", "season", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"schedule_postseason_tuneIn": {
		Name:           "schedule_postseason_tuneIn",
		PathTemplate:   "{ver}/schedule/postseason/tuneIn",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"teamId", "sportId", "season", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "The schedule_postseason_tuneIn endpoint appears to return no data.",
	},
	"schedule_tied": {
		Name:           "schedule_tied",
		PathTemplate:   "{ver}/schedule/games/tied",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"gameTypes", "season", "hydrate", "fields"},
		RequiredParams: [][]string{{"season"}},
		Note:           "",
	},
	"season": {
		Name:           "season",
		PathTemplate:   "{ver}/seasons/{seasonId}",
		PathParamOrder: []string{"ver", "seasonId"},
		PathParams: map[string]PathParamDefinition{
			"ver":      {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"seasonId": {Type: "str", Default: "False", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"sportId", "fields"},
		RequiredParams: [][]string{{"sportId"}},
		Note:           "",
	},
	"seasons": {
		Name:           "seasons",
		PathTemplate:   "{ver}/seasons{all}",
		PathParamOrder: []string{"ver", "all"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"all": {Type: "bool", Default: "", HasDefault: true, TrueValue: "/all", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: false},
		},
		QueryParams:    []string{"season", "sportId", "divisionId", "leagueId", "fields"},
		RequiredParams: [][]string{{"sportId"}, {"divisionId"}, {"leagueId"}},
		Note:           "Include \"all\" parameter with value of True to query all seasons. The divisionId and leagueId parameters are supported when \"all\" is used.",
	},
	"sports": {
		Name:           "sports",
		PathTemplate:   "{ver}/sports",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"sportId", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"sports_players": {
		Name:           "sports_players",
		PathTemplate:   "{ver}/sports/{sportId}/players",
		PathParamOrder: []string{"ver", "sportId"},
		PathParams: map[string]PathParamDefinition{
			"ver":     {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"sportId": {Type: "str", Default: "1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "gameType", "fields"},
		RequiredParams: [][]string{{"season"}},
		Note:           "",
	},
	"standings": {
		Name:           "standings",
		PathTemplate:   "{ver}/standings",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"leagueId", "season", "standingsTypes", "date", "hydrate", "fields"},
		RequiredParams: [][]string{{"leagueId"}},
		Note:           "",
	},
	"stats": {
		Name:           "stats",
		PathTemplate:   "{ver}/stats",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"stats", "playerPool", "position", "teamId", "leagueId", "limit", "offset", "group", "gameType", "season", "sportIds", "sortStat", "order", "hydrate", "fields", "personId", "metrics", "startDate", "endDate"},
		RequiredParams: [][]string{{"stats", "group"}},
		Note:           "If no limit is specified, the response will be limited to 50 records.",
	},
	"stats_leaders": {
		Name:           "stats_leaders",
		PathTemplate:   "{ver}/stats/leaders",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"leaderCategories", "playerPool", "leaderGameTypes", "statGroup", "season", "leagueId", "sportId", "hydrate", "limit", "fields", "statType"},
		RequiredParams: [][]string{{"leaderCategories"}},
		Note:           "If excluding season parameter to get all time leaders, include statType=statsSingleSeason or you will likely not get any results.",
	},
	"stats_streaks": {
		Name:           "stats_streaks",
		PathTemplate:   "{ver}/stats/streaks",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"streakType", "streakSpan", "gameType", "season", "sportId", "limit", "hydrate", "fields"},
		RequiredParams: [][]string{{"streakType", "streakSpan", "season", "sportId", "limit"}},
		Note:           "Valid streakType values: \"hittingStreakOverall\" \"hittingStreakHome\" \"hittingStreakAway\" \"onBaseOverall\" \"onBaseHome\" \"onBaseAway\". Valid streakSpan values: \"career\" \"season\" \"currentStreak\" \"currentStreakInSeason\" \"notable\" \"notableInSeason\".",
	},
	"team": {
		Name:           "team",
		PathTemplate:   "{ver}/teams/{teamId}",
		PathParamOrder: []string{"ver", "teamId"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"teamId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "sportId", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"team_alumni": {
		Name:           "team_alumni",
		PathTemplate:   "{ver}/teams/{teamId}/alumni",
		PathParamOrder: []string{"ver", "teamId"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"teamId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "group", "hydrate", "fields"},
		RequiredParams: [][]string{{"season", "group"}},
		Note:           "",
	},
	"team_coaches": {
		Name:           "team_coaches",
		PathTemplate:   "{ver}/teams/{teamId}/coaches",
		PathParamOrder: []string{"ver", "teamId"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"teamId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "date", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"team_leaders": {
		Name:           "team_leaders",
		PathTemplate:   "{ver}/teams/{teamId}/leaders",
		PathParamOrder: []string{"ver", "teamId"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"teamId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"leaderCategories", "season", "leaderGameTypes", "hydrate", "limit", "fields"},
		RequiredParams: [][]string{{"leaderCategories", "season"}},
		Note:           "",
	},
	"team_personnel": {
		Name:           "team_personnel",
		PathTemplate:   "{ver}/teams/{teamId}/personnel",
		PathParamOrder: []string{"ver", "teamId"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"teamId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"date", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"team_roster": {
		Name:           "team_roster",
		PathTemplate:   "{ver}/teams/{teamId}/roster",
		PathParamOrder: []string{"ver", "teamId"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"teamId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"rosterType", "season", "date", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"team_stats": {
		Name:           "team_stats",
		PathTemplate:   "{ver}/teams/{teamId}/stats",
		PathParamOrder: []string{"ver", "teamId"},
		PathParams: map[string]PathParamDefinition{
			"ver":    {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
			"teamId": {Type: "str", Default: "", HasDefault: false, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "group", "gameType", "stats", "sportIds", "sitCodes", "fields"},
		RequiredParams: [][]string{{"season", "group"}},
		Note:           "Use meta('statGroups') to look up valid values for group, meta('statTypes') for valid values for stats, and meta('situationCodes') for valid values for sitCodes. Use sitCodes with stats=statSplits.",
	},
	"team_uniforms": {
		Name:           "team_uniforms",
		PathTemplate:   "{ver}/uniforms/team",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"teamIds", "season", "fields"},
		RequiredParams: [][]string{{"teamIds"}},
		Note:           "",
	},
	"teams": {
		Name:           "teams",
		PathTemplate:   "{ver}/teams",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "activeStatus", "leagueIds", "sportId", "sportIds", "gameType", "hydrate", "fields"},
		RequiredParams: [][]string{{}},
		Note:           "",
	},
	"teams_affiliates": {
		Name:           "teams_affiliates",
		PathTemplate:   "{ver}/teams/affiliates",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"teamIds", "sportId", "season", "hydrate", "fields"},
		RequiredParams: [][]string{{"teamIds"}},
		Note:           "",
	},
	"teams_history": {
		Name:           "teams_history",
		PathTemplate:   "{ver}/teams/history",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"teamIds", "startSeason", "endSeason", "fields"},
		RequiredParams: [][]string{{"teamIds"}},
		Note:           "",
	},
	"teams_stats": {
		Name:           "teams_stats",
		PathTemplate:   "{ver}/teams/stats",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"season", "sportIds", "group", "gameType", "stats", "order", "sortStat", "fields", "startDate", "endDate"},
		RequiredParams: [][]string{{"season", "group", "stats"}},
		Note:           "Use meta('statGroups') to look up valid values for group, and meta('statTypes') for valid values for stats.",
	},
	"transactions": {
		Name:           "transactions",
		PathTemplate:   "{ver}/transactions",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"teamId", "playerId", "date", "startDate", "endDate", "sportId", "fields"},
		RequiredParams: [][]string{{"teamId"}, {"playerId"}, {"date"}, {"startDate", "endDate"}},
		Note:           "",
	},
	"venue": {
		Name:           "venue",
		PathTemplate:   "{ver}/venues",
		PathParamOrder: []string{"ver"},
		PathParams: map[string]PathParamDefinition{
			"ver": {Type: "str", Default: "v1", HasDefault: true, TrueValue: "", FalseValue: "", LeadingSlash: false, TrailingSlash: false, Required: true},
		},
		QueryParams:    []string{"venueIds", "season", "hydrate", "fields"},
		RequiredParams: [][]string{{"venueIds"}},
		Note:           "",
	},
}

func EndpointNames() []string {
	out := make([]string, len(endpointNames))
	copy(out, endpointNames)
	return out
}

func (c *Client) CallAttendance(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "attendance", params)
}

func CallAttendance(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallAttendance(ctx, params)
}

func (c *Client) CallAwards(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "awards", params)
}

func CallAwards(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallAwards(ctx, params)
}

func (c *Client) CallConferences(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "conferences", params)
}

func CallConferences(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallConferences(ctx, params)
}

func (c *Client) CallDivisions(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "divisions", params)
}

func CallDivisions(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallDivisions(ctx, params)
}

func (c *Client) CallDraft(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "draft", params)
}

func CallDraft(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallDraft(ctx, params)
}

func (c *Client) CallGame(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game", params)
}

func CallGame(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGame(ctx, params)
}

func (c *Client) CallGamePace(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "gamePace", params)
}

func CallGamePace(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGamePace(ctx, params)
}

func (c *Client) CallGameBoxscore(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_boxscore", params)
}

func CallGameBoxscore(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameBoxscore(ctx, params)
}

func (c *Client) CallGameChanges(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_changes", params)
}

func CallGameChanges(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameChanges(ctx, params)
}

func (c *Client) CallGameColor(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_color", params)
}

func CallGameColor(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameColor(ctx, params)
}

func (c *Client) CallGameColorDiff(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_color_diff", params)
}

func CallGameColorDiff(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameColorDiff(ctx, params)
}

func (c *Client) CallGameColorTimestamps(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_color_timestamps", params)
}

func CallGameColorTimestamps(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameColorTimestamps(ctx, params)
}

func (c *Client) CallGameContent(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_content", params)
}

func CallGameContent(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameContent(ctx, params)
}

func (c *Client) CallGameContextMetrics(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_contextMetrics", params)
}

func CallGameContextMetrics(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameContextMetrics(ctx, params)
}

func (c *Client) CallGameDiff(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_diff", params)
}

func CallGameDiff(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameDiff(ctx, params)
}

func (c *Client) CallGameLinescore(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_linescore", params)
}

func CallGameLinescore(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameLinescore(ctx, params)
}

func (c *Client) CallGamePlayByPlay(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_playByPlay", params)
}

func CallGamePlayByPlay(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGamePlayByPlay(ctx, params)
}

func (c *Client) CallGameTimestamps(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_timestamps", params)
}

func CallGameTimestamps(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameTimestamps(ctx, params)
}

func (c *Client) CallGameUniforms(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_uniforms", params)
}

func CallGameUniforms(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameUniforms(ctx, params)
}

func (c *Client) CallGameWinProbability(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "game_winProbability", params)
}

func CallGameWinProbability(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallGameWinProbability(ctx, params)
}

func (c *Client) CallHighLow(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "highLow", params)
}

func CallHighLow(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallHighLow(ctx, params)
}

func (c *Client) CallHomeRunDerby(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "homeRunDerby", params)
}

func CallHomeRunDerby(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallHomeRunDerby(ctx, params)
}

func (c *Client) CallJobs(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "jobs", params)
}

func CallJobs(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallJobs(ctx, params)
}

func (c *Client) CallJobsDatacasters(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "jobs_datacasters", params)
}

func CallJobsDatacasters(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallJobsDatacasters(ctx, params)
}

func (c *Client) CallJobsOfficialScorers(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "jobs_officialScorers", params)
}

func CallJobsOfficialScorers(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallJobsOfficialScorers(ctx, params)
}

func (c *Client) CallJobsUmpireGames(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "jobs_umpire_games", params)
}

func CallJobsUmpireGames(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallJobsUmpireGames(ctx, params)
}

func (c *Client) CallJobsUmpires(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "jobs_umpires", params)
}

func CallJobsUmpires(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallJobsUmpires(ctx, params)
}

func (c *Client) CallLeague(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "league", params)
}

func CallLeague(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallLeague(ctx, params)
}

func (c *Client) CallLeagueAllStarBallot(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "league_allStarBallot", params)
}

func CallLeagueAllStarBallot(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallLeagueAllStarBallot(ctx, params)
}

func (c *Client) CallLeagueAllStarFinalVote(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "league_allStarFinalVote", params)
}

func CallLeagueAllStarFinalVote(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallLeagueAllStarFinalVote(ctx, params)
}

func (c *Client) CallLeagueAllStarWriteIns(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "league_allStarWriteIns", params)
}

func CallLeagueAllStarWriteIns(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallLeagueAllStarWriteIns(ctx, params)
}

func (c *Client) CallMeta(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "meta", params)
}

func CallMeta(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallMeta(ctx, params)
}

func (c *Client) CallPeople(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "people", params)
}

func CallPeople(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallPeople(ctx, params)
}

func (c *Client) CallPeopleChanges(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "people_changes", params)
}

func CallPeopleChanges(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallPeopleChanges(ctx, params)
}

func (c *Client) CallPeopleFreeAgents(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "people_freeAgents", params)
}

func CallPeopleFreeAgents(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallPeopleFreeAgents(ctx, params)
}

func (c *Client) CallPerson(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "person", params)
}

func CallPerson(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallPerson(ctx, params)
}

func (c *Client) CallPersonStats(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "person_stats", params)
}

func CallPersonStats(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallPersonStats(ctx, params)
}

func (c *Client) CallSchedule(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "schedule", params)
}

func CallSchedule(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSchedule(ctx, params)
}

func (c *Client) CallSchedulePostseason(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "schedule_postseason", params)
}

func CallSchedulePostseason(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSchedulePostseason(ctx, params)
}

func (c *Client) CallSchedulePostseasonSeries(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "schedule_postseason_series", params)
}

func CallSchedulePostseasonSeries(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSchedulePostseasonSeries(ctx, params)
}

func (c *Client) CallSchedulePostseasonTuneIn(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "schedule_postseason_tuneIn", params)
}

func CallSchedulePostseasonTuneIn(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSchedulePostseasonTuneIn(ctx, params)
}

func (c *Client) CallScheduleTied(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "schedule_tied", params)
}

func CallScheduleTied(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallScheduleTied(ctx, params)
}

func (c *Client) CallSeason(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "season", params)
}

func CallSeason(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSeason(ctx, params)
}

func (c *Client) CallSeasons(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "seasons", params)
}

func CallSeasons(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSeasons(ctx, params)
}

func (c *Client) CallSports(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "sports", params)
}

func CallSports(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSports(ctx, params)
}

func (c *Client) CallSportsPlayers(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "sports_players", params)
}

func CallSportsPlayers(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallSportsPlayers(ctx, params)
}

func (c *Client) CallStandings(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "standings", params)
}

func CallStandings(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallStandings(ctx, params)
}

func (c *Client) CallStats(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "stats", params)
}

func CallStats(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallStats(ctx, params)
}

func (c *Client) CallStatsLeaders(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "stats_leaders", params)
}

func CallStatsLeaders(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallStatsLeaders(ctx, params)
}

func (c *Client) CallStatsStreaks(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "stats_streaks", params)
}

func CallStatsStreaks(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallStatsStreaks(ctx, params)
}

func (c *Client) CallTeam(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team", params)
}

func CallTeam(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeam(ctx, params)
}

func (c *Client) CallTeamAlumni(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team_alumni", params)
}

func CallTeamAlumni(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamAlumni(ctx, params)
}

func (c *Client) CallTeamCoaches(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team_coaches", params)
}

func CallTeamCoaches(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamCoaches(ctx, params)
}

func (c *Client) CallTeamLeaders(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team_leaders", params)
}

func CallTeamLeaders(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamLeaders(ctx, params)
}

func (c *Client) CallTeamPersonnel(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team_personnel", params)
}

func CallTeamPersonnel(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamPersonnel(ctx, params)
}

func (c *Client) CallTeamRoster(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team_roster", params)
}

func CallTeamRoster(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamRoster(ctx, params)
}

func (c *Client) CallTeamStats(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team_stats", params)
}

func CallTeamStats(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamStats(ctx, params)
}

func (c *Client) CallTeamUniforms(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "team_uniforms", params)
}

func CallTeamUniforms(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamUniforms(ctx, params)
}

func (c *Client) CallTeams(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "teams", params)
}

func CallTeams(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeams(ctx, params)
}

func (c *Client) CallTeamsAffiliates(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "teams_affiliates", params)
}

func CallTeamsAffiliates(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamsAffiliates(ctx, params)
}

func (c *Client) CallTeamsHistory(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "teams_history", params)
}

func CallTeamsHistory(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamsHistory(ctx, params)
}

func (c *Client) CallTeamsStats(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "teams_stats", params)
}

func CallTeamsStats(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTeamsStats(ctx, params)
}

func (c *Client) CallTransactions(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "transactions", params)
}

func CallTransactions(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallTransactions(ctx, params)
}

func (c *Client) CallVenue(ctx context.Context, params Params) (JSON, error) {
	return c.Get(ctx, "venue", params)
}

func CallVenue(ctx context.Context, params Params) (JSON, error) {
	return DefaultClient.CallVenue(ctx, params)
}
